version: 2.1
jobs:
  push_docker_image:
    docker:
      - image: chalice/alicloud-sdk
        name: ALICLOUD
    parameters:
      test_project_name:
        type: string
      storage_secret_key:
        type: string
      storage_endpoint:
        type: string
      storage_access_id:
        type: string
      storage_name:
        type: string
      docker_username:
        type: string
      docker_password:
        type: string

    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u "<< parameters.docker_username >>" -p "<< parameters.docker_password >>"
      - run: docker build -t << parameters.test_project_name >>/$CIRCLE_PROJECT_REPONAME:latest .
      - run: docker push << parameters.test_project_name >>/$CIRCLE_PROJECT_REPONAME:latest
      - run: docker run -d --name=$CIRCLE_PROJECT_REPONAME --env VUE_APP_API_URL='https://api.chalice.top/' << parameters.test_project_name >>/$CIRCLE_PROJECT_REPONAME:latest ping google.com
      - run: docker exec -it $CIRCLE_PROJECT_REPONAME npm run build
      - run: docker cp $CIRCLE_PROJECT_REPONAME:/usr/src/app/dist dist
      - run: ossutil config -e << parameters.storage_endpoint >> -i << parameters.storage_access_id >> -k << parameters.storage_secret_key >>  -L CH --config-file ./key
      - run: ossutil cp dist/ oss://<< parameters.storage_name >>/ -r -f --config-file ./key
      - run: butil --e << parameters.storage_endpoint >> --i << parameters.storage_access_id >> --k << parameters.storage_secret_key >> --b << parameters.storage_name >> --o clear_all
      - run: butil --e << parameters.storage_endpoint >> --i << parameters.storage_access_id >> --k << parameters.storage_secret_key >> --b << parameters.storage_name >> --o add
workflows:
  version: 2
  staging_pipeline:
    jobs:
      - push_docker_image:
          test_project_name: $TEST_PROJECT_NAME
          storage_secret_key: $STORAGE_SECRET_KEY
          storage_endpoint: $STORAGE_ENDPOINT
          storage_access_id: $STORAGE_ACCESS_ID
          storage_name: $STORAGE_NAME
          docker_username: $DOCKER_USERNAME
          docker_password: $DOCKER_PASSWORD
          filters:
            branches:
              only:
                - master

  staging_mobile_pipeline:
    jobs:
      - push_docker_image:
          test_project_name: $TEST_PROJECT_NAME
          storage_secret_key: $STORAGE_SECRET_KEY
          storage_endpoint: $STORAGE_ENDPOINT
          storage_access_id: $STORAGE_ACCESS_ID
          storage_name: $STORAGE_NAME_MOBILE
          docker_username: $DOCKER_USERNAME
          docker_password: $DOCKER_PASSWORD
          filters:
            branches:
              only:
                - mobile
